# Walrus Sites Configuration for MoveTree
# Testnet context configuration

sites:
  - name: "movetree-testnet"
    network: "testnet"
    domain: "movetree.walrus.gg"
    description: "MoveTree LinkTree profiles on Sui testnet"

  - name: "movetree-mainnet"
    network: "mainnet"
    domain: "movetree.walrus.gg"
    description: "MoveTree LinkTree profiles on Sui mainnet"

# Site builder configuration
builder:
  framework: "vite"
  build_command: "npm run build"
  output_directory: "packages/ui/dist"

# Deployment settings
deployment:
  auto_deploy: true
  branch: "main"
  environment: "production"

# Resource management
resources:
  max_sites_per_user: 10
  storage_limit_mb: 100
