[build]
builder = "NIXPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "3001"
NODE_ENV = "production"
